package writer

import (
	"strings"
	"testing"
	"time"

	"github.com/thanhhaudev/github-stats/pkg/github"
	"github.com/thanhhaudev/github-stats/pkg/wakatime"
)

func TestFormatCountLine(t *testing.T) {
	tests := []struct {
		name     string
		label    string
		value    int64
		singular string
		plural   string
		want     string
	}{
		{
			name:     "uses singular form for one",
			label:    "🔥 Current Streak:",
			value:    1,
			singular: "day",
			plural:   "days",
			want:     "1 day",
		},
		{
			name:     "uses plural form for many",
			label:    "📅 Active Days:",
			value:    2,
			singular: "day",
			plural:   "days",
			want:     "2 days",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := formatCountLine(tt.label, tt.value, tt.singular, tt.plural)
			if !strings.Contains(got, tt.label) || !strings.Contains(got, tt.want) {
				t.Fatalf("unexpected line:\nwant label %q and value %q\ngot  %q", tt.label, tt.want, got)
			}
		})
	}
}

func TestMakeStatBlock(t *testing.T) {
	got := makeStatBlock("📈 Coding Streak",
		formatCountLine("🔥 Current Streak:", 1, "day", "days"),
		formatCountLine("🏆 Longest Streak:", 2, "day", "days"),
	)

	if !strings.Contains(got, "**📈 Coding Streak**") {
		t.Fatalf("missing title in output: %q", got)
	}
	if !strings.Contains(got, "1 day") {
		t.Fatalf("missing singular value in output: %q", got)
	}
	if !strings.Contains(got, "2 days") {
		t.Fatalf("missing plural value in output: %q", got)
	}
	if !strings.Contains(got, "```text") {
		t.Fatalf("missing code block in output: %q", got)
	}
}

func TestFormatStatLine(t *testing.T) {
	tests := []struct {
		name  string
		label string
		value string
		want  string
	}{
		{
			name:  "ascii label keeps existing padding",
			label: "📊 AI Contribution:",
			value: "99.7%",
			want:  "📊 AI Contribution:       99.7%\n",
		},
		{
			name:  "emoji label uses display width for padding",
			label: "🤖 Generated by AI:",
			value: "244,293 lines",
			want:  "🤖 Generated by AI:       244,293 lines\n",
		},
		{
			name:  "coding streak labels align with emoji width",
			label: "🔥 Current Streak:",
			value: "14 days",
			want:  "🔥 Current Streak:        14 days\n",
		},
		{
			name:  "active days label aligns with emoji width",
			label: "📅 Active Days:",
			value: "370 days",
			want:  "📅 Active Days:           370 days\n",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := formatStatLine(tt.label, tt.value)
			if got != tt.want {
				t.Fatalf("formatStatLine(%q, %q) = %q, want %q", tt.label, tt.value, got, tt.want)
			}
		})
	}
}

func TestMakeCodingStreakList(t *testing.T) {
	tests := []struct {
		name          string
		stats         *wakatime.AllTimeSinceTodayStats
		currentStreak int
		longestStreak int
		expected      []string // strings that should be present in output
		shouldBeEmpty bool
	}{
		{
			name:          "nil stats and no streaks returns empty string",
			stats:         nil,
			currentStreak: 0,
			longestStreak: 0,
			expected:      []string{},
			shouldBeEmpty: true,
		},
		{
			name:          "works without WakaTime but with streaks",
			stats:         nil,
			currentStreak: 7,
			longestStreak: 30,
			expected: []string{
				"📈 Coding Streak",
				"🔥 Current Streak:",
				"🏆 Longest Streak:",
				"7 days",
				"30 days",
			},
			shouldBeEmpty: false,
		},
		{
			name:          "valid stats with real streak data",
			currentStreak: 14,
			longestStreak: 45,
			stats: &wakatime.AllTimeSinceTodayStats{
				Data: struct {
					TotalSeconds      float64 `json:"total_seconds"`
					Text              string  `json:"text"`
					Decimal           string  `json:"decimal"`
					Digital           string  `json:"digital"`
					DailyAverage      float64 `json:"daily_average"`
					IsUpToDate        bool    `json:"is_up_to_date"`
					PercentCalculated float64 `json:"percent_calculated"`
					Range             struct {
						Start     string `json:"start"`
						StartDate string `json:"start_date"`
						StartText string `json:"start_text"`
						End       string `json:"end"`
						EndDate   string `json:"end_date"`
						EndText   string `json:"end_text"`
						Timezone  string `json:"timezone"`
					} `json:"range"`
					Timeout float64 `json:"timeout"`
				}{
					TotalSeconds: 4979819.370848,
					Text:         "1,383 hrs 16 mins",
					DailyAverage: 13437.0, // ~3.7 hours
					Range: struct {
						Start     string `json:"start"`
						StartDate string `json:"start_date"`
						StartText string `json:"start_text"`
						End       string `json:"end"`
						EndDate   string `json:"end_date"`
						EndText   string `json:"end_text"`
						Timezone  string `json:"timezone"`
					}{
						StartDate: "2024-08-01",
						EndDate:   "2025-12-21",
					},
				},
			},
			expected: []string{
				"📈 Coding Streak",
				"🔥 Current Streak:",
				"🏆 Longest Streak:",
				"📊 Daily Average:",
				"💪 Total Coding Time:",
				"🎯 Coding Consistency:",
				"📅 Active Days:",
				"1,383 hrs 16 mins",
				"14 days",
				"45 days",
			},
			shouldBeEmpty: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := MakeCodingStreakList(tt.stats, tt.currentStreak, tt.longestStreak)

			if tt.shouldBeEmpty {
				if result != "" {
					t.Errorf("Expected empty string, got: %s", result)
				}
				return
			}

			for _, expected := range tt.expected {
				if !strings.Contains(result, expected) {
					t.Errorf("Expected output to contain '%s', but it didn't.\nGot: %s", expected, result)
				}
			}

			// Verify it contains the markdown code block
			if !strings.Contains(result, "```text") {
				t.Error("Expected output to contain markdown code block")
			}
		})
	}
}

func TestMakeAIStatsList(t *testing.T) {
	tests := []struct {
		name        string
		aiAdd       int64
		humanAdd    int64
		inTokens    int64
		outTokens   int64
		avgPrompt   float64
		wakaRange   string
		empty       bool
		contains    []string
		notContains []string
	}{
		{
			name:  "no activity returns empty",
			empty: true,
		},
		{
			name:      "Average Prompt uses ai_average_prompt_length when populated",
			aiAdd:     1500,
			inTokens:  120_000,
			outTokens: 350_000,
			avgPrompt: 7200,
			wakaRange: "all_time",
			contains: []string{
				"🤖 My AI Footprint",
				"Generated by AI:       1,500 lines",
				"Written by Hand:       0 lines",
				"AI Contribution:       100.0%",
				"Tokens In / Out:       120.0K / 350.0K",
				"Average Prompt:        7.2K chars",
			},
		},
		{
			name:      "small token counts use addCommas; prompt row hidden when both zero",
			aiAdd:     20,
			inTokens:  999,
			wakaRange: "all_time",
			contains: []string{
				"Tokens In / Out:       999 / 0",
			},
			notContains: []string{"Average Prompt:", "Total Prompt Chars:"},
		},
		{
			name:      "title shows weekly variant for last_7_days",
			aiAdd:     100,
			inTokens:  500,
			wakaRange: "last_7_days",
			contains:  []string{"**🤖 My Week in AI**"},
		},
		{
			name:      "title shows monthly variant for last_30_days",
			aiAdd:     100,
			inTokens:  500,
			wakaRange: "last_30_days",
			contains:  []string{"**🤖 My Month in AI**"},
		},
		{
			name:      "title shows 6-month variant for last_6_months",
			aiAdd:     100,
			inTokens:  500,
			wakaRange: "last_6_months",
			contains:  []string{"**🤖 My 6 Months in AI**"},
		},
		{
			name:      "title shows yearly variant for last_year",
			aiAdd:     100,
			inTokens:  500,
			wakaRange: "last_year",
			contains:  []string{"**🤖 My Year in AI**"},
		},
		{
			name:      "title falls back to default for unknown range",
			aiAdd:     100,
			inTokens:  500,
			wakaRange: "bogus",
			contains:  []string{"**🤖 My AI Footprint**"},
		},
		{
			name:     "title falls back to default when range is empty",
			aiAdd:    100,
			inTokens: 500,
			contains: []string{"**🤖 My AI Footprint**"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := MakeAIStatsList(tt.aiAdd, tt.humanAdd, tt.inTokens, tt.outTokens, tt.avgPrompt, tt.wakaRange)

			if tt.empty {
				if got != "" {
					t.Errorf("expected empty string, got %q", got)
				}
				return
			}

			for _, want := range tt.contains {
				if !strings.Contains(got, want) {
					t.Errorf("expected output to contain %q, got:\n%s", want, got)
				}
			}
			for _, banned := range tt.notContains {
				if strings.Contains(got, banned) {
					t.Errorf("expected output to NOT contain %q, got:\n%s", banned, got)
				}
			}
		})
	}
}

func TestHumanizeCount(t *testing.T) {
	tests := []struct {
		name  string
		input int64
		want  string
	}{
		{
			name:  "uses commas below one thousand",
			input: 999,
			want:  "999",
		},
		{
			name:  "formats thousands",
			input: 1_500,
			want:  "1.5K",
		},
		{
			name:  "rolls over rounded thousands into millions",
			input: 999_950,
			want:  "1.0M",
		},
		{
			name:  "formats millions",
			input: 2_500_000,
			want:  "2.5M",
		},
		{
			name:  "formats billions",
			input: 1_260_000_000,
			want:  "1.3B",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := humanizeCount(tt.input)
			if got != tt.want {
				t.Fatalf("humanizeCount(%d) = %q, want %q", tt.input, got, tt.want)
			}
		})
	}
}

func TestMakeCommitTimesOfDayList(t *testing.T) {
	commits := []github.Commit{
		{CommittedDate: time.Date(2026, 5, 8, 7, 0, 0, 0, time.UTC)},
		{CommittedDate: time.Date(2026, 5, 8, 7, 30, 0, 0, time.UTC)},
		{CommittedDate: time.Date(2026, 5, 8, 13, 0, 0, 0, time.UTC)},
		{CommittedDate: time.Date(2026, 5, 8, 19, 0, 0, 0, time.UTC)},
		{CommittedDate: time.Date(2026, 5, 8, 23, 30, 0, 0, time.UTC)},
	}

	got := MakeCommitTimesOfDayList(commits, false, "1")

	want := strings.Join([]string{
		"**🕒 I'm An Early Bird 🐤**",
		"",
		"```text",
		"🌅 Morning" + strings.Repeat(" ", 15) + "2 commits" + strings.Repeat(" ", 11) + "██████████░░░░░░░░░░░░░░░   40.00%",
		"🌞 Daytime" + strings.Repeat(" ", 15) + "1 commit" + strings.Repeat(" ", 12) + "█████░░░░░░░░░░░░░░░░░░░░   20.00%",
		"🌆 Evening" + strings.Repeat(" ", 15) + "1 commit" + strings.Repeat(" ", 12) + "█████░░░░░░░░░░░░░░░░░░░░   20.00%",
		"🌙 Night" + strings.Repeat(" ", 17) + "1 commit" + strings.Repeat(" ", 12) + "█████░░░░░░░░░░░░░░░░░░░░   20.00%",
		"```",
		"",
		"",
	}, "\n")

	if got != want {
		t.Fatalf("unexpected output:\nwant:\n%s\n\ngot:\n%s", want, got)
	}
}
