package writer

import (
	"fmt"
	"math"
	"sort"
	"strings"
	"time"
	"unicode"
	"unicode/utf8"

	"github.com/thanhhaudev/github-stats/pkg/github"
	"github.com/thanhhaudev/github-stats/pkg/wakatime"
)

const (
	nameLength        = 25
	descriptionLength = 20
	graphLength       = 25
)

type Data struct {
	Name        string
	Description string
	Percent     float64
	Hours       int
	Minutes     int
	Seconds     int
}

const (
	Morning WeekTime = iota
	Daytime
	Evening
	Night
)

type WeekTime int

func (w WeekTime) String() string {
	return longWeekTimeNames[w]
}

// MakeLanguageAndToolList returns a list of languages and tools used in the repositories
func MakeLanguageAndToolList(l map[string][2]interface{}, totalSize int) string {
	if len(l) == 0 {
		return ""
	}

	// Create a map to store the sizes for sorting
	sizeMap := make(map[string]int)
	for key, value := range l {
		sizeMap[key] = value[1].(int)
	}

	res := strings.Builder{}
	for _, k := range sortMapByValue(sizeMap) {
		c := l[k][0].(string)
		s := l[k][1].(int)
		fmt.Fprintf(&res, "![%s](https://img.shields.io/badge/%s-%05.2f%%25-%s?&logo=%s&labelColor=151b23)\n", k, k, float64(s)/float64(totalSize)*100, c[1:], k)
	}

	return "**💬 Languages & Tools**\n\n" + res.String() + "\n\n"
}

// MakeWakaActivityList returns a list of activities
func MakeWakaActivityList(s *wakatime.Stats, i []string, version string) string {
	if s == nil || len(i) == 0 {
		return ""
	}

	var res string
	for _, v := range i {
		switch v {
		case "LANGUAGES":
			res = res + "💬 Languages:" + makeList(buildWakaData(s.Data.Languages), version) + "\n"
		case "EDITORS":
			res = res + "📝 Editors:" + makeList(buildWakaData(s.Data.Editors), version) + "\n"
		case "OPERATING_SYSTEMS":
			res = res + "💻 Operating Systems:" + makeList(buildWakaData(s.Data.OperatingSystems), version) + "\n"
		case "PROJECTS":
			res = res + "📦 Projects:" + makeList(buildWakaData(s.Data.Projects), version) + "\n"
		}
	}

	res = strings.TrimSuffix(res, "\n") // trim last newline

	return fmt.Sprintf("**%s**\n\n", wakaRangeNames[s.Data.Range]) + "```text\n" + res + "```\n\n"
}

func buildWakaData(i []wakatime.StatsItem) []Data {
	var (
		data      []Data
		otherData Data
	)
	for _, d := range i {
		if d.Minutes < 10 && d.Hours == 0 || d.Name == "Other" {
			otherData.Percent += d.Percent
			otherData.Hours += d.Hours
			otherData.Minutes += d.Minutes
			otherData.Seconds += d.Seconds

			continue
		}

		data = append(data, Data{
			Name:        d.Name,
			Description: d.Text,
			Percent:     d.Percent,
			Hours:       d.Hours,
			Minutes:     d.Minutes,
			Seconds:     d.Seconds,
		})
	}

	if otherData.Percent > 0 {
		data = append(data, Data{
			Name:        "Others",
			Description: formatTime(otherData.Hours, otherData.Minutes),
			Percent:     otherData.Percent,
		})
	}

	return data
}

// MakeLastUpdatedOn returns a string with the last updated time
func MakeLastUpdatedOn(t string) string {
	return fmt.Sprintf("\n\n⏳ *Last updated on %s*", t)
}

// MakeCodingStreakList returns coding streak statistics from commit data and WakaTime all-time data.
func MakeCodingStreakList(s *wakatime.AllTimeSinceTodayStats, currentStreak, longestStreak int) string {
	if s == nil && currentStreak == 0 && longestStreak == 0 {
		return ""
	}

	lines := []string{
		formatCountLine("🔥 Current Streak:", int64(currentStreak), "day", "days"),
		formatCountLine("🏆 Longest Streak:", int64(longestStreak), "day", "days"),
	}

	if s != nil {
		dailyAvg := int(s.Data.DailyAverage)
		dailyAvgHours := dailyAvg / 3600
		dailyAvgMinutes := (dailyAvg % 3600) / 60

		startDate, _ := time.Parse("2006-01-02", s.Data.Range.StartDate)
		endDate, _ := time.Parse("2006-01-02", s.Data.Range.EndDate)
		totalDays := int(endDate.Sub(startDate).Hours() / 24)

		var activeDays int
		if s.Data.DailyAverage > 0 {
			activeDays = int(s.Data.TotalSeconds / s.Data.DailyAverage)
		}

		var consistencyPercent float64
		if totalDays > 0 {
			consistencyPercent = (float64(activeDays) / float64(totalDays)) * 100
		}

		lines = append(lines,
			formatStatLine("📊 Daily Average:", fmt.Sprintf("%d hrs %d mins", dailyAvgHours, dailyAvgMinutes)),
			formatStatLine("💪 Total Coding Time:", s.Data.Text),
			formatStatLine("🎯 Coding Consistency:", fmt.Sprintf("%.1f%%", consistencyPercent)),
			formatCountLine("📅 Active Days:", int64(activeDays), "day", "days"),
		)
	}

	return makeStatBlock("📈 Coding Streak", lines...)
}

// MakeAIStatsList returns a summary of AI vs human coding attribution from WakaTime.
func MakeAIStatsList(aiAdd, humanAdd, inTokens, outTokens int64, avgPrompt float64, wakaRange string) string {
	if aiAdd == 0 && inTokens == 0 {
		return ""
	}

	title, ok := aiFootprintTitles[wakaRange]
	if !ok {
		title = aiFootprintTitles["all_time"]
	}

	totalAdd := aiAdd + humanAdd
	var aiContribution float64
	if totalAdd > 0 {
		aiContribution = float64(aiAdd) / float64(totalAdd) * 100
	}

	lines := []string{
		formatCountLine("🤖 Generated by AI:", aiAdd, "line", "lines"),
		formatCountLine("👤 Written by Hand:", humanAdd, "line", "lines"),
		formatStatLine("📊 AI Contribution:", fmt.Sprintf("%.1f%%", aiContribution)),
		formatStatLine("🔤 Tokens In / Out:", humanizeCount(inTokens)+" / "+humanizeCount(outTokens)),
	}

	if avgPrompt > 0 {
		lines = append(lines, formatCountLineFormatted("💬 Average Prompt:", int64(math.Round(avgPrompt)), "char", "chars", humanizeCount))
	}

	return makeStatBlock(title, lines...)
}

// humanizeCount formats large numbers with compact suffixes; falls back to addCommas under 1,000.
func humanizeCount(n int64) string {
	if n < 1_000 {
		return addCommas(int(n))
	}

	type suffix struct {
		value float64
		label string
	}

	suffixes := []suffix{
		{value: 1_000_000_000_000, label: "T"},
		{value: 1_000_000_000, label: "B"},
		{value: 1_000_000, label: "M"},
		{value: 1_000, label: "K"},
	}

	for i, s := range suffixes {
		if float64(n) < s.value {
			continue
		}

		scaled := float64(n) / s.value
		if scaled >= 999.95 && i > 0 {
			next := suffixes[i-1]
			return fmt.Sprintf("%.1f%s", float64(n)/next.value, next.label)
		}

		return fmt.Sprintf("%.1f%s", scaled, s.label)
	}

	return addCommas(int(n))
}

// MakeCommitTimesOfDayList returns a list of commits made during different times of the day
func MakeCommitTimesOfDayList(commits []github.Commit, simplifyTitle bool, version string) string {
	if len(commits) == 0 {
		return ""
	}

	timeRanges := map[WeekTime][2]int{
		Morning: {6, 12},
		Daytime: {12, 18},
		Evening: {18, 23},
		Night:   {23, 6},
	}

	total := len(commits)
	counts := make(map[WeekTime]int)

	for _, commit := range commits {
		hour := commit.CommittedDate.Hour()
		for period, rangeHours := range timeRanges {
			if rangeHours[0] < rangeHours[1] { // if the range is not across midnight
				if hour >= rangeHours[0] && hour < rangeHours[1] {
					counts[period]++
					break
				}
			} else { // if the range is across midnight
				if hour >= rangeHours[0] || hour < rangeHours[1] {
					counts[period]++
					break
				}
			}
		}
	}

	var data []Data
	var topWeek WeekTime
	var topVal int

	for i, n := range longWeekTimeNames {
		weekTime := WeekTime(i)
		weekCommit := counts[weekTime]
		if weekCommit > topVal {
			topVal = weekCommit
			topWeek = weekTime
		}

		data = append(data, Data{
			Name: fmt.Sprintf("%s %s", timesOfDayEmoji[weekTime], n),
			Description: fmt.Sprintf("%s %s", addCommas(weekCommit), func() string {
				if weekCommit > 1 {
					return "commits"
				}

				return "commit"
			}()),
			Percent: float64(weekCommit) / float64(total) * 100,
		})
	}

	status := longTimesOfDayStatuses[topWeek]
	if simplifyTitle {
		if (data[0].Percent + data[1].Percent) > (data[2].Percent + data[3].Percent) {
			status = timesOfDayStatuses[0]
		} else {
			status = timesOfDayStatuses[1]
		}
	}

	return fmt.Sprintf("**🕒 I'm %s**\n\n", status) + "```text" + makeList(data, version) + "```\n\n"
}

// MakeCommitDaysOfWeekList returns a list of commits made on each day of the week
func MakeCommitDaysOfWeekList(wd map[time.Weekday]int, total int, version string) string {
	if total == 0 {
		return ""
	}

	var (
		topName string
		topVal  int
		data    []Data
	)

	weekdays := []time.Weekday{
		time.Sunday,
		time.Monday,
		time.Tuesday,
		time.Wednesday,
		time.Thursday,
		time.Friday,
		time.Saturday,
	}

	for _, weekday := range weekdays {
		if wd[weekday] > topVal {
			topVal = wd[weekday]
			topName = weekday.String()
		}

		data = append(data, Data{
			Name: weekday.String(),
			Description: fmt.Sprintf("%s %s", addCommas(wd[weekday]), func() string {
				if wd[weekday] > 1 {
					return "commits"
				}

				return "commit"
			}()),
			Percent: float64(wd[weekday]) / float64(total) * 100,
		})
	}

	return fmt.Sprintf("**📅 I'm Most Productive on %s**\n\n", topName) + "```text" + makeList(data, version) + "```\n\n"
}

// MakeLanguagePerRepoList returns a list of languages and the percentage of repositories that use them
func MakeLanguagePerRepoList(r []github.Repository, version string) string {
	if len(r) == 0 {
		return ""
	}

	var (
		count   float64
		topName string
		topNum  int
		data    []Data
		repos   = make(map[string]int)
	)

	for _, v := range r {
		if v.PrimaryLanguage == nil {
			continue // Skip repositories without a primary language
		}

		repos[v.PrimaryLanguage.Name]++
		count++
	}

	if len(repos) == 0 {
		return ""
	}

	// Create a list of Data structs
	for _, name := range sortMapByValue(repos) {
		num := repos[name]
		if num > topNum { // find top language
			topNum = num
			topName = name
		}

		data = append(data, Data{
			Name: name,
			Description: fmt.Sprintf("%s %s", addCommas(num), func() string {
				if num > 1 {
					return "repos"
				}
				return "repo"
			}()),
			Percent: float64(num) / count * 100,
		})
	}

	return fmt.Sprintf("**🔥 I Mostly Code in %s**\n\n", topName) + "```text" + makeList(data, version) + "```\n\n"
}

func makeList(d []Data, version string) string {
	if len(d) == 0 {
		return "\nNo data available\n"
	}

	var b strings.Builder

	for _, val := range d {
		b.WriteString(formatData(val, version))
	}

	b.WriteString("\n")

	return b.String()
}

func makeProgressBar(p float64) string {
	filledChar := "█"
	emptyChar := "░"

	filledLength := int(math.Round(p / (100 / graphLength)))
	emptyLength := graphLength - filledLength

	return strings.Repeat(filledChar, filledLength) + strings.Repeat(emptyChar, emptyLength)
}

func makeProgressBarV2(p float64) string {
	filledChar := "🟩"
	halfFilledChar := "🟨"
	emptyChar := "⬜"

	percentagePerBlock := float64(100 / graphLength)
	filledLength := int(math.Floor(p / percentagePerBlock))
	remainingPercentage := p - (float64(filledLength) * percentagePerBlock)
	halfFilledLength := 0
	if remainingPercentage > 0 {
		halfFilledLength = 1
	}
	emptyLength := graphLength - filledLength - halfFilledLength

	return strings.Repeat(filledChar, filledLength) + strings.Repeat(halfFilledChar, halfFilledLength) + strings.Repeat(emptyChar, emptyLength)
}

func formatData(data Data, version string) string {
	var b strings.Builder

	n := truncateString(data.Name, nameLength)
	d := truncateString(data.Description, descriptionLength)

	b.WriteString("\n")
	b.WriteString(n)
	b.WriteString(strings.Repeat(" ", max(0, nameLength-displayWidth(n))))
	b.WriteString(d)
	b.WriteString(strings.Repeat(" ", max(0, descriptionLength-displayWidth(d))))

	if version == "2" {
		b.WriteString(makeProgressBarV2(data.Percent))
	} else {
		b.WriteString(makeProgressBar(data.Percent))
	}

	b.WriteString("   ")
	b.WriteString(formatPercent(data.Percent))

	return b.String()
}

func formatPercent(p float64) string {
	return fmt.Sprintf("%05.2f%%", p)
}

func max(a, b int) int {
	if a > b {
		return a
	}

	return b
}

func truncateString(s string, l int) string {
	if utf8.RuneCountInString(s) > l {
		return s[:l]
	}

	return s
}

func addCommas(n int) string {
	str := fmt.Sprintf("%d", n)
	var result []string
	for i, c := range str {
		if (len(str)-i)%3 == 0 && i != 0 {
			result = append(result, ",")
		}
		result = append(result, string(c))
	}

	return strings.Join(result, "")
}

func makeStatBlock(title string, lines ...string) string {
	var b strings.Builder
	b.WriteString("**")
	b.WriteString(title)
	b.WriteString("**\n\n")
	b.WriteString("```text\n")
	for _, line := range lines {
		b.WriteString(line)
	}
	b.WriteString("```\n\n")

	return b.String()
}

// formatStatLine formats a stat line with consistent padding between label and value.
func formatStatLine(label, value string) string {
	const labelWidth = 26
	labelLen := displayWidth(label)
	padding := labelWidth - labelLen
	if padding < 0 {
		padding = 0
	}
	return label + strings.Repeat(" ", padding) + value + "\n"
}

func displayWidth(s string) int {
	width := 0
	for _, r := range s {
		switch {
		case unicode.Is(unicode.Mn, r):
			continue
		case isWideRune(r):
			width += 2
		default:
			width++
		}
	}

	return width
}

func isWideRune(r rune) bool {
	switch {
	case r >= 0x1F300 && r <= 0x1FAFF:
		return true
	case r >= 0x2600 && r <= 0x26FF:
		return true
	case r >= 0x2700 && r <= 0x27BF:
		return true
	case r >= 0x2E80 && r <= 0xA4CF:
		return true
	case r >= 0xAC00 && r <= 0xD7A3:
		return true
	case r >= 0xF900 && r <= 0xFAFF:
		return true
	case r >= 0xFE10 && r <= 0xFE19:
		return true
	case r >= 0xFE30 && r <= 0xFE6F:
		return true
	case r >= 0xFF00 && r <= 0xFF60:
		return true
	case r >= 0xFFE0 && r <= 0xFFE6:
		return true
	default:
		return false
	}
}

func formatCountLine(label string, value int64, singular, plural string) string {
	return formatCountLineFormatted(label, value, singular, plural, func(n int64) string {
		return addCommas(int(n))
	})
}

func formatCountLineFormatted(label string, value int64, singular, plural string, format func(int64) string) string {
	unit := plural
	if value == 1 {
		unit = singular
	}

	return formatStatLine(label, fmt.Sprintf("%s %s", format(value), unit))
}

func formatTime(hours, minutes int) string {
	var result string
	if hours > 0 {
		result += fmt.Sprintf("%d %s", hours, func() string {
			if hours > 1 {
				return "hrs"
			}

			return "hr"
		}())
	}

	if minutes > 0 {
		result += fmt.Sprintf(" %d %s", minutes, func() string {
			if minutes > 1 {
				return "mins"
			}

			return "min"
		}())
	}

	return strings.TrimSpace(result)
}

// sortMapByValue sorts a map by its values in descending order
func sortMapByValue(m map[string]int) []string {
	keys := make([]string, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}

	sort.Slice(keys, func(i, j int) bool {
		return m[keys[i]] > m[keys[j]]
	})

	return keys
}
